# Generated by Django 4.2.7 on 2026-04-16 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('gender_probability', models.FloatField()),
                ('sample_size', models.IntegerField()),
                ('age', models.IntegerField()),
                ('age_group', models.CharField(max_length=20)),
                ('country_id', models.CharField(max_length=10)),
                ('country_probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
